name: lab3
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ":5432"
    volumes:
      - wp_labs_postgres3:/var/lib/postgresql/data
    networks:
      - wp_labs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_LOGGING: ${DB_LOGGING}
      PORT: 4200
      AUTH_COOKIE_SECURE: ${AUTH_COOKIE_SECURE}
      AUTH_OAUTH_SUCCESS_REDIRECT: ${AUTH_OAUTH_SUCCESS_REDIRECT}
      YANDEX_OAUTH_CLIENT_ID: ${YANDEX_OAUTH_CLIENT_ID}
      YANDEX_OAUTH_CLIENT_SECRET: ${YANDEX_OAUTH_CLIENT_SECRET}
      YANDEX_OAUTH_REDIRECT_URI: ${YANDEX_OAUTH_REDIRECT_URI}
      YANDEX_OAUTH_SCOPE: ${YANDEX_OAUTH_SCOPE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - wp_labs_network

  migrate:
    build: .
    command: npm run db:migrate
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_LOGGING: ${DB_LOGGING}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wp_labs_network


volumes:
  wp_labs_postgres3:

networks:
  wp_labs_network:
